[OZSDK-22] Implementacao de dutos
ozmap/ozmap-sdk pull request #42
Opened 2024-05-27 13:58 UTC by czirkeosta

2024-06-06 10:31 UTC, christianzirke reviewed
Comentário vazio pra completar o review

2024-06-18 18:29 UTC, gabriel-marioto approved these changes

2024-06-19 12:29 UTC, leandroschabarum requested changes

2024-06-19 12:29 UTC, leandroschabarum commented on src/interface/model/Duct.ts
> +// type DuctStructureSchemaType = {
Acho que podemos remover esse código comentado.

2024-06-25 11:04 UTC, merged